---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: managed1
  namespace: managed1
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
#  proxy:
#    httpProxy: <proxy>
#    httpsProxy: <proxy>
#    noProxy: <domain-or-ips-comma-separated>
#  additionalNTPSources:
#    - 0.rhel.pool.ntp.org
  clusterRef:
    name: managed1
    namespace: managed1
  sshAuthorizedKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJki56BeBPdyYpB+7RK+K2olyjoZyQn13Oc3NJUCIij4 nday@nday.csb'
#  agentLabelSelector:
#    matchLabels:
#      cluster-name: mce
  pullSecretRef:
    name: pull-secret
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: managed1
  cpuArchitecture: x86_64
# User modify ignition during discovery
#   ignitionConfigOverride: ''
