---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "master-0"
  labels:
    infraenvs.agent-install.openshift.io: "mce"
  name: master-0
  namespace: mce
spec:
  automatedCleaningMode: metadata
  rootDeviceHints:
    deviceName: /dev/vda
  bmc:
    address: redfish-virtualmedia+http://192.168.188.50:8000/redfish/v1/Systems/4053d06f-4be8-48fe-88f8-55015f5e8fe7
    credentialsName: bmc-secret
    disableCertificateVerification: true
  bootMACAddress: 'aa:aa:aa:aa:aa:01'
  bootMode: UEFI
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "master-1"
  labels:
    infraenvs.agent-install.openshift.io: "mce"
  name: master-1
  namespace: mce
spec:
  automatedCleaningMode: metadata
  rootDeviceHints:
    deviceName: /dev/vda
  bmc:
    address: redfish-virtualmedia+http://192.168.188.50:8000/redfish/v1/Systems/20f27c85-1405-46ea-878e-0543387372a3
    credentialsName: bmc-secret
    disableCertificateVerification: true
  bootMACAddress: 'aa:aa:aa:aa:aa:02'
  bootMode: UEFI
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "master-2"
  labels:
    infraenvs.agent-install.openshift.io: "mce"
  name: master-2
  namespace: mce
spec:
  automatedCleaningMode: metadata
  rootDeviceHints:
    deviceName: /dev/vda
  bmc:
    address: redfish-virtualmedia+http://192.168.188.50:8000/redfish/v1/Systems/122c8bc4-4371-4d8e-939d-3dbce12d0864
    disableCertificateVerification: true
  bootMACAddress: 'aa:aa:aa:aa:aa:03'
  bootMode: UEFI
  online: true
