#/etc/NetworkManager/dnsmasq.d/01-DNS-dnsmasq-routednet.nickday.biz.conf
# local dns
local=/routednet.labs.nickday.biz/
addn-hosts=/etc/virsh-routednet-dnsmasq.hosts
address=/apps-crc.testing/127.0.0.1

domain-needed
bogus-priv

# Automatically add <domain> to simple names in a hosts-file.
expand-hosts

# Upstream public
no-poll
server=8.8.8.8
